### ISSUE TITLE
Stacking PanelBase Ram.

### ISSUE THREAD

**Issue by DeadLineSS13** [unitystation/stationhub#89] opened 2021-03-18 12:05 UTC
![image](https://user-images.githubusercontent.com/41364830/111623392-61a9ef80-87fb-11eb-8c13-1f9e9ee14393.png)
So maybe there problem with loop Ram.

**Comment by RedlineTriad** [comment] 2021-04-05 20:11
This is most likely a duplicate of #70

**Closed as completed by RedlineTriad** 2021-04-05 20:11 UTC
Labels: bug
