### ISSUE TITLE
cannot make new accounts on the new hub

### ISSUE THREAD

**Issue by Bod9001** [unitystation/stationhub#112] opened 2021-08-15 17:12 UTC
apparently nothing happens when you click the create account button

**Comment by corp-0** [comment] 2021-08-15 20:42
I could reproduce on MacOS Catalina and Windows 10, I would assume it also happens in Linux since it definetively is related to #109 and it works if you have previously done a log in.

**Comment by corp-0** [comment] 2021-08-17 20:03
fixed on #120

**Closed as completed by corp-0** 2021-08-17 20:03 UTC
Labels: bug
